### ISSUE TITLE
License and copyright notice missing

### ISSUE THREAD

**Issue by Booli** [datjan/esp8266-victron-mppt-solarchargecontroller#6]
Hey @datjan,

I see that this code has been based on the original: [repository](https://github.com/physee/Victron.Arduino-ESP8266)

That code is licensed MIT and has Copyright notice, it would be good practice to include that in your project.

**Comment by datjan** [comment]
Hey Booli,

You are right. I created the LICENSE file.

regards

**Comment by Booli** [comment]
Thanks for the quick response!
